# Generated by Django 5.0 on 2023-12-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = []

  operations = [
      migrations.CreateModel(
          name="Article",
          fields=[
              ("id", models.AutoField(primary_key=True, serialize=False)),
              ("created_time", models.DateTimeField(auto_now_add=True)),
              ("updated_time", models.DateTimeField(auto_now=True)),
              ("title", models.CharField(max_length=200, verbose_name="title")),
              ("body", models.TextField(verbose_name="body")),
              ("views",
               models.PositiveIntegerField(default=0, verbose_name="views")),
          ],
          options={
              "verbose_name": "article",
              "verbose_name_plural": "articles",
              "ordering": ["-created_time"],
          },
      ),
  ]
